# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

dryRun: Optional[bool]
"""
Prevent the Domain provider from taking certain actions
"""

key: Optional[str]
"""
(DEPRECATED) A Gandi API key
"""

personalAccessToken: Optional[str]
"""
A Gandi API Personal Access Token
"""

sharingId: Optional[str]
"""
(DEPRECATED) A Gandi Sharing ID
"""

url: Optional[str]
"""
The Gandi API URL
"""

