// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi
{
    [Obsolete(@"gandi.index/dnsseckey.DnssecKey has been deprecated in favor of gandi.domains/dnsseckey.DNSSecKey")]
    [GandiResourceType("gandi:index/dnssecKey:DnssecKey")]
    public partial class DnssecKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// DNSSEC algorithm type
        /// </summary>
        [Output("algorithm")]
        public Output<int> Algorithm { get; private set; } = null!;

        /// <summary>
        /// Domain name
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// DNSSEC public key
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// DNSSEC key type
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a DnssecKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DnssecKey(string name, DnssecKeyArgs args, CustomResourceOptions? options = null)
            : base("gandi:index/dnssecKey:DnssecKey", name, args ?? new DnssecKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DnssecKey(string name, Input<string> id, DnssecKeyState? state = null, CustomResourceOptions? options = null)
            : base("gandi:index/dnssecKey:DnssecKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DnssecKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DnssecKey Get(string name, Input<string> id, DnssecKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new DnssecKey(name, id, state, options);
        }
    }

    public sealed class DnssecKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DNSSEC algorithm type
        /// </summary>
        [Input("algorithm", required: true)]
        public Input<int> Algorithm { get; set; } = null!;

        /// <summary>
        /// Domain name
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// DNSSEC public key
        /// </summary>
        [Input("publicKey", required: true)]
        public Input<string> PublicKey { get; set; } = null!;

        /// <summary>
        /// DNSSEC key type
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public DnssecKeyArgs()
        {
        }
        public static new DnssecKeyArgs Empty => new DnssecKeyArgs();
    }

    public sealed class DnssecKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DNSSEC algorithm type
        /// </summary>
        [Input("algorithm")]
        public Input<int>? Algorithm { get; set; }

        /// <summary>
        /// Domain name
        /// </summary>
        [Input("domain")]
        public Input<string>? Domain { get; set; }

        /// <summary>
        /// DNSSEC public key
        /// </summary>
        [Input("publicKey")]
        public Input<string>? PublicKey { get; set; }

        /// <summary>
        /// DNSSEC key type
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public DnssecKeyState()
        {
        }
        public static new DnssecKeyState Empty => new DnssecKeyState();
    }
}
