// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi
{
    [Obsolete(@"gandi.index/getlivednsdomain.getLivednsDomain has been deprecated in favor of gandi.livedns/getdomain.getDomain")]
    public static class GetLivednsDomain
    {
        public static Task<GetLivednsDomainResult> InvokeAsync(GetLivednsDomainArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetLivednsDomainResult>("gandi:index/getLivednsDomain:getLivednsDomain", args ?? new GetLivednsDomainArgs(), options.WithDefaults());

        public static Output<GetLivednsDomainResult> Invoke(GetLivednsDomainInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetLivednsDomainResult>("gandi:index/getLivednsDomain:getLivednsDomain", args ?? new GetLivednsDomainInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetLivednsDomainArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetLivednsDomainArgs()
        {
        }
        public static new GetLivednsDomainArgs Empty => new GetLivednsDomainArgs();
    }

    public sealed class GetLivednsDomainInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetLivednsDomainInvokeArgs()
        {
        }
        public static new GetLivednsDomainInvokeArgs Empty => new GetLivednsDomainInvokeArgs();
    }


    [OutputType]
    public sealed class GetLivednsDomainResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetLivednsDomainResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
