// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gandi
{
    [Obsolete(@"gandi.index/simplehostinginstance.SimplehostingInstance has been deprecated in favor of gandi.simplehosting/instance.Instance")]
    [GandiResourceType("gandi:index/simplehostingInstance:SimplehostingInstance")]
    public partial class SimplehostingInstance : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The name of the database type ('mysql' or 'pgsql')
        /// </summary>
        [Output("databaseName")]
        public Output<string> DatabaseName { get; private set; } = null!;

        /// <summary>
        /// The name of the language ('php', 'python', 'nodejs' or 'ruby')
        /// </summary>
        [Output("languageName")]
        public Output<string> LanguageName { get; private set; } = null!;

        /// <summary>
        /// The datacenter location of the instance ('FR' or 'LU')
        /// </summary>
        [Output("location")]
        public Output<string> Location { get; private set; } = null!;

        /// <summary>
        /// The name of the SimpleHosting instance
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
        /// </summary>
        [Output("size")]
        public Output<string> Size { get; private set; } = null!;


        /// <summary>
        /// Create a SimplehostingInstance resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SimplehostingInstance(string name, SimplehostingInstanceArgs args, CustomResourceOptions? options = null)
            : base("gandi:index/simplehostingInstance:SimplehostingInstance", name, args ?? new SimplehostingInstanceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SimplehostingInstance(string name, Input<string> id, SimplehostingInstanceState? state = null, CustomResourceOptions? options = null)
            : base("gandi:index/simplehostingInstance:SimplehostingInstance", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SimplehostingInstance resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SimplehostingInstance Get(string name, Input<string> id, SimplehostingInstanceState? state = null, CustomResourceOptions? options = null)
        {
            return new SimplehostingInstance(name, id, state, options);
        }
    }

    public sealed class SimplehostingInstanceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the database type ('mysql' or 'pgsql')
        /// </summary>
        [Input("databaseName", required: true)]
        public Input<string> DatabaseName { get; set; } = null!;

        /// <summary>
        /// The name of the language ('php', 'python', 'nodejs' or 'ruby')
        /// </summary>
        [Input("languageName", required: true)]
        public Input<string> LanguageName { get; set; } = null!;

        /// <summary>
        /// The datacenter location of the instance ('FR' or 'LU')
        /// </summary>
        [Input("location", required: true)]
        public Input<string> Location { get; set; } = null!;

        /// <summary>
        /// The name of the SimpleHosting instance
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
        /// </summary>
        [Input("size", required: true)]
        public Input<string> Size { get; set; } = null!;

        public SimplehostingInstanceArgs()
        {
        }
        public static new SimplehostingInstanceArgs Empty => new SimplehostingInstanceArgs();
    }

    public sealed class SimplehostingInstanceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the database type ('mysql' or 'pgsql')
        /// </summary>
        [Input("databaseName")]
        public Input<string>? DatabaseName { get; set; }

        /// <summary>
        /// The name of the language ('php', 'python', 'nodejs' or 'ruby')
        /// </summary>
        [Input("languageName")]
        public Input<string>? LanguageName { get; set; }

        /// <summary>
        /// The datacenter location of the instance ('FR' or 'LU')
        /// </summary>
        [Input("location")]
        public Input<string>? Location { get; set; }

        /// <summary>
        /// The name of the SimpleHosting instance
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The size of the SimpleHosting instance ('s+', 'm', 'l' or 'xxl')
        /// </summary>
        [Input("size")]
        public Input<string>? Size { get; set; }

        public SimplehostingInstanceState()
        {
        }
        public static new SimplehostingInstanceState Empty => new SimplehostingInstanceState();
    }
}
