// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gandi

import (
	"context"
	"reflect"

	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: gandi.index/getgluerecord.getGlueRecord has been deprecated in favor of gandi.domains/getgluerecord.getGlueRecord
func LookupGlueRecord(ctx *pulumi.Context, args *LookupGlueRecordArgs, opts ...pulumi.InvokeOption) (*LookupGlueRecordResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGlueRecordResult
	err := ctx.Invoke("gandi:index/getGlueRecord:getGlueRecord", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGlueRecord.
type LookupGlueRecordArgs struct {
	Name string `pulumi:"name"`
	Zone string `pulumi:"zone"`
}

// A collection of values returned by getGlueRecord.
type LookupGlueRecordResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string   `pulumi:"id"`
	Ips  []string `pulumi:"ips"`
	Name string   `pulumi:"name"`
	Zone string   `pulumi:"zone"`
}

func LookupGlueRecordOutput(ctx *pulumi.Context, args LookupGlueRecordOutputArgs, opts ...pulumi.InvokeOption) LookupGlueRecordResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupGlueRecordResult, error) {
			args := v.(LookupGlueRecordArgs)
			r, err := LookupGlueRecord(ctx, &args, opts...)
			var s LookupGlueRecordResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupGlueRecordResultOutput)
}

// A collection of arguments for invoking getGlueRecord.
type LookupGlueRecordOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (LookupGlueRecordOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGlueRecordArgs)(nil)).Elem()
}

// A collection of values returned by getGlueRecord.
type LookupGlueRecordResultOutput struct{ *pulumi.OutputState }

func (LookupGlueRecordResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGlueRecordResult)(nil)).Elem()
}

func (o LookupGlueRecordResultOutput) ToLookupGlueRecordResultOutput() LookupGlueRecordResultOutput {
	return o
}

func (o LookupGlueRecordResultOutput) ToLookupGlueRecordResultOutputWithContext(ctx context.Context) LookupGlueRecordResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupGlueRecordResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupGlueRecordResultOutput) Ips() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) []string { return v.Ips }).(pulumi.StringArrayOutput)
}

func (o LookupGlueRecordResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupGlueRecordResultOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGlueRecordResult) string { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGlueRecordResultOutput{})
}
