// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gandi

import (
	"context"
	"reflect"

	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: gandi.index/getlivednsdomain.getLivednsDomain has been deprecated in favor of gandi.livedns/getdomain.getDomain
func LookupLivednsDomain(ctx *pulumi.Context, args *LookupLivednsDomainArgs, opts ...pulumi.InvokeOption) (*LookupLivednsDomainResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLivednsDomainResult
	err := ctx.Invoke("gandi:index/getLivednsDomain:getLivednsDomain", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLivednsDomain.
type LookupLivednsDomainArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getLivednsDomain.
type LookupLivednsDomainResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}

func LookupLivednsDomainOutput(ctx *pulumi.Context, args LookupLivednsDomainOutputArgs, opts ...pulumi.InvokeOption) LookupLivednsDomainResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupLivednsDomainResult, error) {
			args := v.(LookupLivednsDomainArgs)
			r, err := LookupLivednsDomain(ctx, &args, opts...)
			var s LookupLivednsDomainResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupLivednsDomainResultOutput)
}

// A collection of arguments for invoking getLivednsDomain.
type LookupLivednsDomainOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupLivednsDomainOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLivednsDomainArgs)(nil)).Elem()
}

// A collection of values returned by getLivednsDomain.
type LookupLivednsDomainResultOutput struct{ *pulumi.OutputState }

func (LookupLivednsDomainResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLivednsDomainResult)(nil)).Elem()
}

func (o LookupLivednsDomainResultOutput) ToLookupLivednsDomainResultOutput() LookupLivednsDomainResultOutput {
	return o
}

func (o LookupLivednsDomainResultOutput) ToLookupLivednsDomainResultOutputWithContext(ctx context.Context) LookupLivednsDomainResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupLivednsDomainResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLivednsDomainResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupLivednsDomainResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLivednsDomainResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLivednsDomainResultOutput{})
}
