// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gandi

import (
	"context"
	"reflect"

	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: gandi.index/getlivednsdomainns.getLivednsDomainNs has been deprecated in favor of gandi.livedns/getdomainnameserver.getDomainNameserver
func GetLivednsDomainNs(ctx *pulumi.Context, args *GetLivednsDomainNsArgs, opts ...pulumi.InvokeOption) (*GetLivednsDomainNsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLivednsDomainNsResult
	err := ctx.Invoke("gandi:index/getLivednsDomainNs:getLivednsDomainNs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLivednsDomainNs.
type GetLivednsDomainNsArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getLivednsDomainNs.
type GetLivednsDomainNsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string   `pulumi:"id"`
	Name        string   `pulumi:"name"`
	Nameservers []string `pulumi:"nameservers"`
}

func GetLivednsDomainNsOutput(ctx *pulumi.Context, args GetLivednsDomainNsOutputArgs, opts ...pulumi.InvokeOption) GetLivednsDomainNsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetLivednsDomainNsResult, error) {
			args := v.(GetLivednsDomainNsArgs)
			r, err := GetLivednsDomainNs(ctx, &args, opts...)
			var s GetLivednsDomainNsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetLivednsDomainNsResultOutput)
}

// A collection of arguments for invoking getLivednsDomainNs.
type GetLivednsDomainNsOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetLivednsDomainNsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLivednsDomainNsArgs)(nil)).Elem()
}

// A collection of values returned by getLivednsDomainNs.
type GetLivednsDomainNsResultOutput struct{ *pulumi.OutputState }

func (GetLivednsDomainNsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLivednsDomainNsResult)(nil)).Elem()
}

func (o GetLivednsDomainNsResultOutput) ToGetLivednsDomainNsResultOutput() GetLivednsDomainNsResultOutput {
	return o
}

func (o GetLivednsDomainNsResultOutput) ToGetLivednsDomainNsResultOutputWithContext(ctx context.Context) GetLivednsDomainNsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetLivednsDomainNsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetLivednsDomainNsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetLivednsDomainNsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetLivednsDomainNsResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetLivednsDomainNsResultOutput) Nameservers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetLivednsDomainNsResult) []string { return v.Nameservers }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLivednsDomainNsResultOutput{})
}
