// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gandi

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "gandi:index/dnssecKey:DnssecKey":
		r = &DnssecKey{}
	case "gandi:index/domain:Domain":
		r = &Domain{}
	case "gandi:index/emailForwarding:EmailForwarding":
		r = &EmailForwarding{}
	case "gandi:index/glueRecord:GlueRecord":
		r = &GlueRecord{}
	case "gandi:index/livednsDomain:LivednsDomain":
		r = &LivednsDomain{}
	case "gandi:index/livednsRecord:LivednsRecord":
		r = &LivednsRecord{}
	case "gandi:index/mailbox:Mailbox":
		r = &Mailbox{}
	case "gandi:index/nameservers:Nameservers":
		r = &Nameservers{}
	case "gandi:index/simplehostingInstance:SimplehostingInstance":
		r = &SimplehostingInstance{}
	case "gandi:index/simplehostingVhost:SimplehostingVhost":
		r = &SimplehostingVhost{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:gandi" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"gandi",
		"index/dnssecKey",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/domain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/emailForwarding",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/glueRecord",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/livednsDomain",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/livednsRecord",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/mailbox",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/nameservers",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/simplehostingInstance",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"gandi",
		"index/simplehostingVhost",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"gandi",
		&pkg{version},
	)
}
