// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gandi

import (
	"context"
	"reflect"

	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain
type LivednsDomain struct {
	pulumi.CustomResourceState

	// Enable or disable the automatic creation of snapshots when records are changed
	AutomaticSnapshots pulumi.BoolPtrOutput `pulumi:"automaticSnapshots"`
	// The FQDN of the domain
	Name pulumi.StringOutput `pulumi:"name"`
	// The SOA TTL for the domain
	//
	// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
	// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
	Ttl pulumi.IntPtrOutput `pulumi:"ttl"`
}

// NewLivednsDomain registers a new resource with the given unique name, arguments, and options.
func NewLivednsDomain(ctx *pulumi.Context,
	name string, args *LivednsDomainArgs, opts ...pulumi.ResourceOption) (*LivednsDomain, error) {
	if args == nil {
		args = &LivednsDomainArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource LivednsDomain
	err := ctx.RegisterResource("gandi:index/livednsDomain:LivednsDomain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLivednsDomain gets an existing LivednsDomain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLivednsDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LivednsDomainState, opts ...pulumi.ResourceOption) (*LivednsDomain, error) {
	var resource LivednsDomain
	err := ctx.ReadResource("gandi:index/livednsDomain:LivednsDomain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering LivednsDomain resources.
type livednsDomainState struct {
	// Enable or disable the automatic creation of snapshots when records are changed
	AutomaticSnapshots *bool `pulumi:"automaticSnapshots"`
	// The FQDN of the domain
	Name *string `pulumi:"name"`
	// The SOA TTL for the domain
	//
	// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
	// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
	Ttl *int `pulumi:"ttl"`
}

type LivednsDomainState struct {
	// Enable or disable the automatic creation of snapshots when records are changed
	AutomaticSnapshots pulumi.BoolPtrInput
	// The FQDN of the domain
	Name pulumi.StringPtrInput
	// The SOA TTL for the domain
	//
	// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
	// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
	Ttl pulumi.IntPtrInput
}

func (LivednsDomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*livednsDomainState)(nil)).Elem()
}

type livednsDomainArgs struct {
	// Enable or disable the automatic creation of snapshots when records are changed
	AutomaticSnapshots *bool `pulumi:"automaticSnapshots"`
	// The FQDN of the domain
	Name *string `pulumi:"name"`
	// The SOA TTL for the domain
	//
	// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
	// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
	Ttl *int `pulumi:"ttl"`
}

// The set of arguments for constructing a LivednsDomain resource.
type LivednsDomainArgs struct {
	// Enable or disable the automatic creation of snapshots when records are changed
	AutomaticSnapshots pulumi.BoolPtrInput
	// The FQDN of the domain
	Name pulumi.StringPtrInput
	// The SOA TTL for the domain
	//
	// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
	// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
	Ttl pulumi.IntPtrInput
}

func (LivednsDomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*livednsDomainArgs)(nil)).Elem()
}

type LivednsDomainInput interface {
	pulumi.Input

	ToLivednsDomainOutput() LivednsDomainOutput
	ToLivednsDomainOutputWithContext(ctx context.Context) LivednsDomainOutput
}

func (*LivednsDomain) ElementType() reflect.Type {
	return reflect.TypeOf((**LivednsDomain)(nil)).Elem()
}

func (i *LivednsDomain) ToLivednsDomainOutput() LivednsDomainOutput {
	return i.ToLivednsDomainOutputWithContext(context.Background())
}

func (i *LivednsDomain) ToLivednsDomainOutputWithContext(ctx context.Context) LivednsDomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LivednsDomainOutput)
}

// LivednsDomainArrayInput is an input type that accepts LivednsDomainArray and LivednsDomainArrayOutput values.
// You can construct a concrete instance of `LivednsDomainArrayInput` via:
//
//	LivednsDomainArray{ LivednsDomainArgs{...} }
type LivednsDomainArrayInput interface {
	pulumi.Input

	ToLivednsDomainArrayOutput() LivednsDomainArrayOutput
	ToLivednsDomainArrayOutputWithContext(context.Context) LivednsDomainArrayOutput
}

type LivednsDomainArray []LivednsDomainInput

func (LivednsDomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LivednsDomain)(nil)).Elem()
}

func (i LivednsDomainArray) ToLivednsDomainArrayOutput() LivednsDomainArrayOutput {
	return i.ToLivednsDomainArrayOutputWithContext(context.Background())
}

func (i LivednsDomainArray) ToLivednsDomainArrayOutputWithContext(ctx context.Context) LivednsDomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LivednsDomainArrayOutput)
}

// LivednsDomainMapInput is an input type that accepts LivednsDomainMap and LivednsDomainMapOutput values.
// You can construct a concrete instance of `LivednsDomainMapInput` via:
//
//	LivednsDomainMap{ "key": LivednsDomainArgs{...} }
type LivednsDomainMapInput interface {
	pulumi.Input

	ToLivednsDomainMapOutput() LivednsDomainMapOutput
	ToLivednsDomainMapOutputWithContext(context.Context) LivednsDomainMapOutput
}

type LivednsDomainMap map[string]LivednsDomainInput

func (LivednsDomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LivednsDomain)(nil)).Elem()
}

func (i LivednsDomainMap) ToLivednsDomainMapOutput() LivednsDomainMapOutput {
	return i.ToLivednsDomainMapOutputWithContext(context.Background())
}

func (i LivednsDomainMap) ToLivednsDomainMapOutputWithContext(ctx context.Context) LivednsDomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LivednsDomainMapOutput)
}

type LivednsDomainOutput struct{ *pulumi.OutputState }

func (LivednsDomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**LivednsDomain)(nil)).Elem()
}

func (o LivednsDomainOutput) ToLivednsDomainOutput() LivednsDomainOutput {
	return o
}

func (o LivednsDomainOutput) ToLivednsDomainOutputWithContext(ctx context.Context) LivednsDomainOutput {
	return o
}

// Enable or disable the automatic creation of snapshots when records are changed
func (o LivednsDomainOutput) AutomaticSnapshots() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *LivednsDomain) pulumi.BoolPtrOutput { return v.AutomaticSnapshots }).(pulumi.BoolPtrOutput)
}

// The FQDN of the domain
func (o LivednsDomainOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *LivednsDomain) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The SOA TTL for the domain
//
// Deprecated: This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
// See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
func (o LivednsDomainOutput) Ttl() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *LivednsDomain) pulumi.IntPtrOutput { return v.Ttl }).(pulumi.IntPtrOutput)
}

type LivednsDomainArrayOutput struct{ *pulumi.OutputState }

func (LivednsDomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*LivednsDomain)(nil)).Elem()
}

func (o LivednsDomainArrayOutput) ToLivednsDomainArrayOutput() LivednsDomainArrayOutput {
	return o
}

func (o LivednsDomainArrayOutput) ToLivednsDomainArrayOutputWithContext(ctx context.Context) LivednsDomainArrayOutput {
	return o
}

func (o LivednsDomainArrayOutput) Index(i pulumi.IntInput) LivednsDomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *LivednsDomain {
		return vs[0].([]*LivednsDomain)[vs[1].(int)]
	}).(LivednsDomainOutput)
}

type LivednsDomainMapOutput struct{ *pulumi.OutputState }

func (LivednsDomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*LivednsDomain)(nil)).Elem()
}

func (o LivednsDomainMapOutput) ToLivednsDomainMapOutput() LivednsDomainMapOutput {
	return o
}

func (o LivednsDomainMapOutput) ToLivednsDomainMapOutputWithContext(ctx context.Context) LivednsDomainMapOutput {
	return o
}

func (o LivednsDomainMapOutput) MapIndex(k pulumi.StringInput) LivednsDomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *LivednsDomain {
		return vs[0].(map[string]*LivednsDomain)[vs[1].(string)]
	}).(LivednsDomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LivednsDomainInput)(nil)).Elem(), &LivednsDomain{})
	pulumi.RegisterInputType(reflect.TypeOf((*LivednsDomainArrayInput)(nil)).Elem(), LivednsDomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*LivednsDomainMapInput)(nil)).Elem(), LivednsDomainMap{})
	pulumi.RegisterOutputType(LivednsDomainOutput{})
	pulumi.RegisterOutputType(LivednsDomainArrayOutput{})
	pulumi.RegisterOutputType(LivednsDomainMapOutput{})
}
