// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gandi:livedns/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    public readonly automaticSnapshots!: pulumi.Output<boolean | undefined>;
    /**
     * The FQDN of the domain
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainState | undefined;
            resourceInputs["automaticSnapshots"] = state ? state.automaticSnapshots : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            resourceInputs["automaticSnapshots"] = args ? args.automaticSnapshots : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const aliasOpts = { aliases: [{ type: "gandi:index/livednsDomain:LivednsDomain" }] };
        opts = pulumi.mergeOptions(opts, aliasOpts);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    automaticSnapshots?: pulumi.Input<boolean>;
    /**
     * The FQDN of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    ttl?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    automaticSnapshots?: pulumi.Input<boolean>;
    /**
     * The FQDN of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    ttl?: pulumi.Input<number>;
}
