// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pczora/pulumi-gandi/sdk/go/gandi/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Prevent the Domain provider from taking certain actions
func GetDryRun(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "gandi:dryRun")
}

// (DEPRECATED) A Gandi API key
//
// Deprecated: use personalAccessToken instead
func GetKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:key")
}

// A Gandi API Personal Access Token
func GetPersonalAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:personalAccessToken")
}

// (DEPRECATED) A Gandi Sharing ID
//
// Deprecated: use personalAccessToken instead
func GetSharingId(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:sharingId")
}

// The Gandi API URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:url")
}
