# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .dnssec_key import *
from .domain import *
from .email_forwarding import *
from .get_domain import *
from .get_glue_record import *
from .get_livedns_domain import *
from .get_livedns_domain_ns import *
from .get_mailbox import *
from .glue_record import *
from .livedns_domain import *
from .livedns_record import *
from .mailbox import *
from .nameservers import *
from .provider import *
from .simplehosting_instance import *
from .simplehosting_vhost import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_gandi.config as __config
    config = __config
    import pulumi_gandi.domains as __domains
    domains = __domains
    import pulumi_gandi.email as __email
    email = __email
    import pulumi_gandi.livedns as __livedns
    livedns = __livedns
    import pulumi_gandi.simplehosting as __simplehosting
    simplehosting = __simplehosting
else:
    config = _utilities.lazy_import('pulumi_gandi.config')
    domains = _utilities.lazy_import('pulumi_gandi.domains')
    email = _utilities.lazy_import('pulumi_gandi.email')
    livedns = _utilities.lazy_import('pulumi_gandi.livedns')
    simplehosting = _utilities.lazy_import('pulumi_gandi.simplehosting')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gandi",
  "mod": "domains/dNSSecKey",
  "fqn": "pulumi_gandi.domains",
  "classes": {
   "gandi:domains/dNSSecKey:DNSSecKey": "DNSSecKey"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/domain",
  "fqn": "pulumi_gandi.domains",
  "classes": {
   "gandi:domains/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/glueRecord",
  "fqn": "pulumi_gandi.domains",
  "classes": {
   "gandi:domains/glueRecord:GlueRecord": "GlueRecord"
  }
 },
 {
  "pkg": "gandi",
  "mod": "domains/nameservers",
  "fqn": "pulumi_gandi.domains",
  "classes": {
   "gandi:domains/nameservers:Nameservers": "Nameservers"
  }
 },
 {
  "pkg": "gandi",
  "mod": "email/forwarding",
  "fqn": "pulumi_gandi.email",
  "classes": {
   "gandi:email/forwarding:Forwarding": "Forwarding"
  }
 },
 {
  "pkg": "gandi",
  "mod": "email/mailbox",
  "fqn": "pulumi_gandi.email",
  "classes": {
   "gandi:email/mailbox:Mailbox": "Mailbox"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/dnssecKey",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/dnssecKey:DnssecKey": "DnssecKey"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/domain",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/emailForwarding",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/emailForwarding:EmailForwarding": "EmailForwarding"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/glueRecord",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/glueRecord:GlueRecord": "GlueRecord"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/livednsDomain",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/livednsDomain:LivednsDomain": "LivednsDomain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/livednsRecord",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/livednsRecord:LivednsRecord": "LivednsRecord"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/mailbox",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/mailbox:Mailbox": "Mailbox"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/nameservers",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/nameservers:Nameservers": "Nameservers"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/simplehostingInstance",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/simplehostingInstance:SimplehostingInstance": "SimplehostingInstance"
  }
 },
 {
  "pkg": "gandi",
  "mod": "index/simplehostingVhost",
  "fqn": "pulumi_gandi",
  "classes": {
   "gandi:index/simplehostingVhost:SimplehostingVhost": "SimplehostingVhost"
  }
 },
 {
  "pkg": "gandi",
  "mod": "livedns/domain",
  "fqn": "pulumi_gandi.livedns",
  "classes": {
   "gandi:livedns/domain:Domain": "Domain"
  }
 },
 {
  "pkg": "gandi",
  "mod": "livedns/record",
  "fqn": "pulumi_gandi.livedns",
  "classes": {
   "gandi:livedns/record:Record": "Record"
  }
 },
 {
  "pkg": "gandi",
  "mod": "simplehosting/instance",
  "fqn": "pulumi_gandi.simplehosting",
  "classes": {
   "gandi:simplehosting/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "gandi",
  "mod": "simplehosting/vHost",
  "fqn": "pulumi_gandi.simplehosting",
  "classes": {
   "gandi:simplehosting/vHost:VHost": "VHost"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gandi",
  "token": "pulumi:providers:gandi",
  "fqn": "pulumi_gandi",
  "class": "Provider"
 }
]
"""
)
