# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 dry_run: Optional[pulumi.Input[bool]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 personal_access_token: Optional[pulumi.Input[str]] = None,
                 sharing_id: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Provider resource.
        :param pulumi.Input[bool] dry_run: Prevent the Domain provider from taking certain actions
        :param pulumi.Input[str] key: (DEPRECATED) A Gandi API key
        :param pulumi.Input[str] personal_access_token: A Gandi API Personal Access Token
        :param pulumi.Input[str] sharing_id: (DEPRECATED) A Gandi Sharing ID
        :param pulumi.Input[str] url: The Gandi API URL
        """
        if dry_run is not None:
            pulumi.set(__self__, "dry_run", dry_run)
        if key is not None:
            warnings.warn("""use personal_access_token instead""", DeprecationWarning)
            pulumi.log.warn("""key is deprecated: use personal_access_token instead""")
        if key is not None:
            pulumi.set(__self__, "key", key)
        if personal_access_token is not None:
            pulumi.set(__self__, "personal_access_token", personal_access_token)
        if sharing_id is not None:
            warnings.warn("""use personal_access_token instead""", DeprecationWarning)
            pulumi.log.warn("""sharing_id is deprecated: use personal_access_token instead""")
        if sharing_id is not None:
            pulumi.set(__self__, "sharing_id", sharing_id)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @property
    @pulumi.getter(name="dryRun")
    def dry_run(self) -> Optional[pulumi.Input[bool]]:
        """
        Prevent the Domain provider from taking certain actions
        """
        return pulumi.get(self, "dry_run")

    @dry_run.setter
    def dry_run(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "dry_run", value)

    @property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[str]]:
        """
        (DEPRECATED) A Gandi API key
        """
        warnings.warn("""use personal_access_token instead""", DeprecationWarning)
        pulumi.log.warn("""key is deprecated: use personal_access_token instead""")

        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "key", value)

    @property
    @pulumi.getter(name="personalAccessToken")
    def personal_access_token(self) -> Optional[pulumi.Input[str]]:
        """
        A Gandi API Personal Access Token
        """
        return pulumi.get(self, "personal_access_token")

    @personal_access_token.setter
    def personal_access_token(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "personal_access_token", value)

    @property
    @pulumi.getter(name="sharingId")
    def sharing_id(self) -> Optional[pulumi.Input[str]]:
        """
        (DEPRECATED) A Gandi Sharing ID
        """
        warnings.warn("""use personal_access_token instead""", DeprecationWarning)
        pulumi.log.warn("""sharing_id is deprecated: use personal_access_token instead""")

        return pulumi.get(self, "sharing_id")

    @sharing_id.setter
    def sharing_id(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sharing_id", value)

    @property
    @pulumi.getter
    def url(self) -> Optional[pulumi.Input[str]]:
        """
        The Gandi API URL
        """
        return pulumi.get(self, "url")

    @url.setter
    def url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "url", value)


class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dry_run: Optional[pulumi.Input[bool]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 personal_access_token: Optional[pulumi.Input[str]] = None,
                 sharing_id: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        The provider type for the gandi package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] dry_run: Prevent the Domain provider from taking certain actions
        :param pulumi.Input[str] key: (DEPRECATED) A Gandi API key
        :param pulumi.Input[str] personal_access_token: A Gandi API Personal Access Token
        :param pulumi.Input[str] sharing_id: (DEPRECATED) A Gandi Sharing ID
        :param pulumi.Input[str] url: The Gandi API URL
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The provider type for the gandi package. By default, resources use package-wide configuration
        settings, however an explicit `Provider` instance may be created and passed during resource
        construction to achieve fine-grained programmatic control over provider settings. See the
        [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 dry_run: Optional[pulumi.Input[bool]] = None,
                 key: Optional[pulumi.Input[str]] = None,
                 personal_access_token: Optional[pulumi.Input[str]] = None,
                 sharing_id: Optional[pulumi.Input[str]] = None,
                 url: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            __props__.__dict__["dry_run"] = pulumi.Output.from_input(dry_run).apply(pulumi.runtime.to_json) if dry_run is not None else None
            __props__.__dict__["key"] = None if key is None else pulumi.Output.secret(key)
            __props__.__dict__["personal_access_token"] = None if personal_access_token is None else pulumi.Output.secret(personal_access_token)
            __props__.__dict__["sharing_id"] = sharing_id
            __props__.__dict__["url"] = url
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["key", "personalAccessToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'gandi',
            resource_name,
            __props__,
            opts)

    @property
    @pulumi.getter
    def key(self) -> pulumi.Output[Optional[str]]:
        """
        (DEPRECATED) A Gandi API key
        """
        warnings.warn("""use personal_access_token instead""", DeprecationWarning)
        pulumi.log.warn("""key is deprecated: use personal_access_token instead""")

        return pulumi.get(self, "key")

    @property
    @pulumi.getter(name="personalAccessToken")
    def personal_access_token(self) -> pulumi.Output[Optional[str]]:
        """
        A Gandi API Personal Access Token
        """
        return pulumi.get(self, "personal_access_token")

    @property
    @pulumi.getter(name="sharingId")
    def sharing_id(self) -> pulumi.Output[Optional[str]]:
        """
        (DEPRECATED) A Gandi Sharing ID
        """
        warnings.warn("""use personal_access_token instead""", DeprecationWarning)
        pulumi.log.warn("""sharing_id is deprecated: use personal_access_token instead""")

        return pulumi.get(self, "sharing_id")

    @property
    @pulumi.getter
    def url(self) -> pulumi.Output[Optional[str]]:
        """
        The Gandi API URL
        """
        return pulumi.get(self, "url")

