# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetDomainNameserverResult',
    'AwaitableGetDomainNameserverResult',
    'get_domain_nameserver',
    'get_domain_nameserver_output',
]

@pulumi.output_type
class GetDomainNameserverResult:
    """
    A collection of values returned by getDomainNameserver.
    """
    def __init__(__self__, id=None, name=None, nameservers=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if nameservers and not isinstance(nameservers, list):
            raise TypeError("Expected argument 'nameservers' to be a list")
        pulumi.set(__self__, "nameservers", nameservers)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        The FQDN of the domain
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def nameservers(self) -> Sequence[str]:
        """
        A list of nameservers for the domain
        """
        return pulumi.get(self, "nameservers")


class AwaitableGetDomainNameserverResult(GetDomainNameserverResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDomainNameserverResult(
            id=self.id,
            name=self.name,
            nameservers=self.nameservers)


def get_domain_nameserver(name: Optional[str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDomainNameserverResult:
    """
    Use this data source to access information about an existing resource.

    :param str name: The FQDN of the domain
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('gandi:livedns/getDomainNameserver:getDomainNameserver', __args__, opts=opts, typ=GetDomainNameserverResult).value

    return AwaitableGetDomainNameserverResult(
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'),
        nameservers=pulumi.get(__ret__, 'nameservers'))


@_utilities.lift_output_func(get_domain_nameserver)
def get_domain_nameserver_output(name: Optional[pulumi.Input[str]] = None,
                                 opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetDomainNameserverResult]:
    """
    Use this data source to access information about an existing resource.

    :param str name: The FQDN of the domain
    """
    ...
