// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * @deprecated gandi.index/emailforwarding.EmailForwarding has been deprecated in favor of gandi.email/forwarding.Forwarding
 */
export class EmailForwarding extends pulumi.CustomResource {
    /**
     * Get an existing EmailForwarding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EmailForwardingState, opts?: pulumi.CustomResourceOptions): EmailForwarding {
        pulumi.log.warn("EmailForwarding is deprecated: gandi.index/emailforwarding.EmailForwarding has been deprecated in favor of gandi.email/forwarding.Forwarding")
        return new EmailForwarding(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gandi:index/emailForwarding:EmailForwarding';

    /**
     * Returns true if the given object is an instance of EmailForwarding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EmailForwarding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EmailForwarding.__pulumiType;
    }

    /**
     * Forwards to email addresses
     */
    public readonly destinations!: pulumi.Output<string[]>;
    /**
     * Account alias name
     */
    public readonly source!: pulumi.Output<string>;

    /**
     * Create a EmailForwarding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    /** @deprecated gandi.index/emailforwarding.EmailForwarding has been deprecated in favor of gandi.email/forwarding.Forwarding */
    constructor(name: string, args: EmailForwardingArgs, opts?: pulumi.CustomResourceOptions)
    /** @deprecated gandi.index/emailforwarding.EmailForwarding has been deprecated in favor of gandi.email/forwarding.Forwarding */
    constructor(name: string, argsOrState?: EmailForwardingArgs | EmailForwardingState, opts?: pulumi.CustomResourceOptions) {
        pulumi.log.warn("EmailForwarding is deprecated: gandi.index/emailforwarding.EmailForwarding has been deprecated in favor of gandi.email/forwarding.Forwarding")
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EmailForwardingState | undefined;
            resourceInputs["destinations"] = state ? state.destinations : undefined;
            resourceInputs["source"] = state ? state.source : undefined;
        } else {
            const args = argsOrState as EmailForwardingArgs | undefined;
            if ((!args || args.destinations === undefined) && !opts.urn) {
                throw new Error("Missing required property 'destinations'");
            }
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["destinations"] = args ? args.destinations : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EmailForwarding.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering EmailForwarding resources.
 */
export interface EmailForwardingState {
    /**
     * Forwards to email addresses
     */
    destinations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Account alias name
     */
    source?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EmailForwarding resource.
 */
export interface EmailForwardingArgs {
    /**
     * Forwards to email addresses
     */
    destinations: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Account alias name
     */
    source: pulumi.Input<string>;
}
