// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated gandi.index/getgluerecord.getGlueRecord has been deprecated in favor of gandi.domains/getgluerecord.getGlueRecord */
export function getGlueRecord(args: GetGlueRecordArgs, opts?: pulumi.InvokeOptions): Promise<GetGlueRecordResult> {
    pulumi.log.warn("getGlueRecord is deprecated: gandi.index/getgluerecord.getGlueRecord has been deprecated in favor of gandi.domains/getgluerecord.getGlueRecord")

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gandi:index/getGlueRecord:getGlueRecord", {
        "name": args.name,
        "zone": args.zone,
    }, opts);
}

/**
 * A collection of arguments for invoking getGlueRecord.
 */
export interface GetGlueRecordArgs {
    name: string;
    zone: string;
}

/**
 * A collection of values returned by getGlueRecord.
 */
export interface GetGlueRecordResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ips: string[];
    readonly name: string;
    readonly zone: string;
}
/** @deprecated gandi.index/getgluerecord.getGlueRecord has been deprecated in favor of gandi.domains/getgluerecord.getGlueRecord */
export function getGlueRecordOutput(args: GetGlueRecordOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGlueRecordResult> {
    return pulumi.output(args).apply((a: any) => getGlueRecord(a, opts))
}

/**
 * A collection of arguments for invoking getGlueRecord.
 */
export interface GetGlueRecordOutputArgs {
    name: pulumi.Input<string>;
    zone: pulumi.Input<string>;
}
