// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated gandi.index/getlivednsdomainns.getLivednsDomainNs has been deprecated in favor of gandi.livedns/getdomainnameserver.getDomainNameserver */
export function getLivednsDomainNs(args: GetLivednsDomainNsArgs, opts?: pulumi.InvokeOptions): Promise<GetLivednsDomainNsResult> {
    pulumi.log.warn("getLivednsDomainNs is deprecated: gandi.index/getlivednsdomainns.getLivednsDomainNs has been deprecated in favor of gandi.livedns/getdomainnameserver.getDomainNameserver")

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gandi:index/getLivednsDomainNs:getLivednsDomainNs", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getLivednsDomainNs.
 */
export interface GetLivednsDomainNsArgs {
    name: string;
}

/**
 * A collection of values returned by getLivednsDomainNs.
 */
export interface GetLivednsDomainNsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly nameservers: string[];
}
/** @deprecated gandi.index/getlivednsdomainns.getLivednsDomainNs has been deprecated in favor of gandi.livedns/getdomainnameserver.getDomainNameserver */
export function getLivednsDomainNsOutput(args: GetLivednsDomainNsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetLivednsDomainNsResult> {
    return pulumi.output(args).apply((a: any) => getLivednsDomainNs(a, opts))
}

/**
 * A collection of arguments for invoking getLivednsDomainNs.
 */
export interface GetLivednsDomainNsOutputArgs {
    name: pulumi.Input<string>;
}
