// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated gandi.index/getmailbox.getMailbox has been deprecated in favor of gandi.email/getmailbox.getMailbox */
export function getMailbox(args: GetMailboxArgs, opts?: pulumi.InvokeOptions): Promise<GetMailboxResult> {
    pulumi.log.warn("getMailbox is deprecated: gandi.index/getmailbox.getMailbox has been deprecated in favor of gandi.email/getmailbox.getMailbox")

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("gandi:index/getMailbox:getMailbox", {
        "domain": args.domain,
        "mailboxId": args.mailboxId,
    }, opts);
}

/**
 * A collection of arguments for invoking getMailbox.
 */
export interface GetMailboxArgs {
    domain: string;
    mailboxId: string;
}

/**
 * A collection of values returned by getMailbox.
 */
export interface GetMailboxResult {
    readonly domain: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly mailboxId: string;
}
/** @deprecated gandi.index/getmailbox.getMailbox has been deprecated in favor of gandi.email/getmailbox.getMailbox */
export function getMailboxOutput(args: GetMailboxOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMailboxResult> {
    return pulumi.output(args).apply((a: any) => getMailbox(a, opts))
}

/**
 * A collection of arguments for invoking getMailbox.
 */
export interface GetMailboxOutputArgs {
    domain: pulumi.Input<string>;
    mailboxId: pulumi.Input<string>;
}
