// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * @deprecated gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain
 */
export class LivednsDomain extends pulumi.CustomResource {
    /**
     * Get an existing LivednsDomain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: LivednsDomainState, opts?: pulumi.CustomResourceOptions): LivednsDomain {
        pulumi.log.warn("LivednsDomain is deprecated: gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain")
        return new LivednsDomain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gandi:index/livednsDomain:LivednsDomain';

    /**
     * Returns true if the given object is an instance of LivednsDomain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is LivednsDomain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === LivednsDomain.__pulumiType;
    }

    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    public readonly automaticSnapshots!: pulumi.Output<boolean | undefined>;
    /**
     * The FQDN of the domain
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    public readonly ttl!: pulumi.Output<number | undefined>;

    /**
     * Create a LivednsDomain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    /** @deprecated gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain */
    constructor(name: string, args?: LivednsDomainArgs, opts?: pulumi.CustomResourceOptions)
    /** @deprecated gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain */
    constructor(name: string, argsOrState?: LivednsDomainArgs | LivednsDomainState, opts?: pulumi.CustomResourceOptions) {
        pulumi.log.warn("LivednsDomain is deprecated: gandi.index/livednsdomain.LivednsDomain has been deprecated in favor of gandi.livedns/domain.Domain")
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as LivednsDomainState | undefined;
            resourceInputs["automaticSnapshots"] = state ? state.automaticSnapshots : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
        } else {
            const args = argsOrState as LivednsDomainArgs | undefined;
            resourceInputs["automaticSnapshots"] = args ? args.automaticSnapshots : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(LivednsDomain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering LivednsDomain resources.
 */
export interface LivednsDomainState {
    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    automaticSnapshots?: pulumi.Input<boolean>;
    /**
     * The FQDN of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    ttl?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a LivednsDomain resource.
 */
export interface LivednsDomainArgs {
    /**
     * Enable or disable the automatic creation of snapshots when records are changed
     */
    automaticSnapshots?: pulumi.Input<boolean>;
    /**
     * The FQDN of the domain
     */
    name?: pulumi.Input<string>;
    /**
     * The SOA TTL for the domain
     *
     * @deprecated This ttl attribute will be removed on next major release: this attribute should not be exposed to the user.
See https://github.com/go-gandi/terraform-provider-gandi/pull/90 for details.
     */
    ttl?: pulumi.Input<number>;
}
