// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the gandi package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'gandi';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * (DEPRECATED) A Gandi API key
     *
     * @deprecated use personalAccessToken instead
     */
    public readonly key!: pulumi.Output<string | undefined>;
    /**
     * A Gandi API Personal Access Token
     */
    public readonly personalAccessToken!: pulumi.Output<string | undefined>;
    /**
     * (DEPRECATED) A Gandi Sharing ID
     *
     * @deprecated use personalAccessToken instead
     */
    public readonly sharingId!: pulumi.Output<string | undefined>;
    /**
     * The Gandi API URL
     */
    public readonly url!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["dryRun"] = pulumi.output(args ? args.dryRun : undefined).apply(JSON.stringify);
            resourceInputs["key"] = args?.key ? pulumi.secret(args.key) : undefined;
            resourceInputs["personalAccessToken"] = args?.personalAccessToken ? pulumi.secret(args.personalAccessToken) : undefined;
            resourceInputs["sharingId"] = args ? args.sharingId : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key", "personalAccessToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Prevent the Domain provider from taking certain actions
     */
    dryRun?: pulumi.Input<boolean>;
    /**
     * (DEPRECATED) A Gandi API key
     *
     * @deprecated use personalAccessToken instead
     */
    key?: pulumi.Input<string>;
    /**
     * A Gandi API Personal Access Token
     */
    personalAccessToken?: pulumi.Input<string>;
    /**
     * (DEPRECATED) A Gandi Sharing ID
     *
     * @deprecated use personalAccessToken instead
     */
    sharingId?: pulumi.Input<string>;
    /**
     * The Gandi API URL
     */
    url?: pulumi.Input<string>;
}
